apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: merbridge
  name: merbridge
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: merbridge
  name: merbridge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: merbridge
subjects:
- kind: ServiceAccount
  name: merbridge
  namespace: istio-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: merbridge
  name: merbridge
  namespace: linkerd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: merbridge
  name: merbridge
  namespace: linkerd
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: merbridge
  template:
    metadata:
      labels:
        app: merbridge
    spec:
      containers:
      - image: merbridge/merbridge:latest
        imagePullPolicy: Always
        name: merbridge
        args:
        - /app/mbctl
        - -m
        - linkerd
        lifecycle:
          preStop:
            exec:
              command:
              - make
              - clean
        resources: 
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /sys/fs
            name: sys-fs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: merbridge
      serviceAccountName: merbridge
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /sys/fs
        name: sys-fs
