apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: merbridge
  name: merbridge
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: merbridge
  name: merbridge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: merbridge
subjects:
- kind: ServiceAccount
  name: merbridge
  namespace: linkerd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: merbridge
  name: merbridge
  namespace: linkerd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: merbridge
  name: merbridge
  namespace: linkerd
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: merbridge
  template:
    metadata:
      labels:
        app: merbridge
    spec:
      containers:
      - image: ghcr.io/merbridge/merbridge:latest
        imagePullPolicy: Always
        name: merbridge
        args:
        - /app/mbctl
        - -m
        - linkerd
        - --ips-file
        - /host/ips/ips.txt
        - --use-reconnect=false
        lifecycle:
          preStop:
            exec:
              command:
              - make
              - -k
              - clean
        resources: 
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /sys/fs
            name: sys-fs
          - mountPath: /host/ips
            name: host-ips
      initContainers:
      - image: ghcr.io/merbridge/merbridge:latest
        imagePullPolicy: Always
        name: init
        args:
        - sh
        - -c
        - nsenter --net=/host/proc/1/ns/net ip -o addr | awk '{print $4}' | tee /host/ips/ips.txt
        resources: 
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 50Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /host/ips
            name: host-ips
          - mountPath: /host/proc
            name: host-proc
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: merbridge
      serviceAccountName: merbridge
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /sys/fs
        name: sys-fs
      - hostPath:
          path: /proc
        name: host-proc
      - emptyDir: {}
        name: host-ips
